import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <title>My Pokémon Memory Game</title>
        <meta name="description" content="A fun Pokémon memory game where you match Pokémon." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://example.com/styles.css" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
